CREATE TABLE recipes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(500) NOT NULL,
  prep_time VARCHAR(25),
  cook_time VARCHAR(25),
  total_time VARCHAR(25),
  yield_min INTEGER,
  yield_max INTEGER,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now()
)